### ISSUE TITLE
replace tarsum with archive-sum

### ISSUE THREAD

**Issue by wookietreiber** [idiv-biodiversity/submit-scripts#2]

**Comment by mai00fti** [comment]
I checked whether archive-sum is able to detect missing files in an archive.
To create this situation I did the following

```
cp ~/tmp /tmp
cd /tmp
tar -c tmp -f tmp.tar
tar tvf tmp.tar | tail -1
# gives me the file 'tmp/example.out/', which I now delete from the archive
tar --delete tmp/example.out/ -f tmp.tar
# check if it is really gone
tar tvf tmp.tar | grep 'tmp/example.out/'
```
Now, I have a tar ball where one file of the original archive is missing. 
I'd like to use the -c option from archive-sum to compare the archive with the original data:
```
archive-sum --quiet -c . tmp.tar 
#Error reading '.': .
```
This returns the error that it cannot read the directory.. This happens with whatever directory I choose
```
archive-sum --quiet -c ~/ tmp.tar 
#Error reading '/home/hertelj/': /home/hertelj/
```

I guess that the C program archive-sum only checks if the files inside the tar ball exist in the directory, similar to `tar --compare`.
However, I'd like to check whether the tar ball contains **exactly** the files that are in directory. That means, that I also need to know if all of the original files are inside the archive.

Listing the archives content and calling `diff` on this output and the output of the directory listing of the original directory actually showed the difference.

`tar` has the option `-W|--verify` which can be set during the tar ball creation. This might be a solution, if it works. It needs a test case..
